### ISSUE TITLE
Use asyncio

### ISSUE THREAD

**Issue by ooliver1** [dreamywashere/profile-views-booster#3]
[asyncio](https://docs.aiohttp.org/en/stable/glossary.html#term-asyncio) would be much more fit for this as python threading is still blocked by the [GIL](https://docs.python.org/3/glossary.html#term-global-interpreter-lock)

asyncio with aiohttp would mean that multiple HTTP requests can be going on "at once" (just the waiting part) which is what this program is mostly based off

i know, im bored

**Comment by dreamywashere** [comment]
thanks for the suggestion ig
